### ISSUE TITLE
Figma

### ISSUE THREAD

**Issue by shijiezhou1** [chingu-voyages/v43-tier2-team-22#20]
[https://www.figma.com/file/fGDRrzfQILMFmfxyhaiKlQ/Chat-App-Mood-Board?node-id=0-1&t=RZYssx3xUn9TIS0N-0]([https://www.figma.com/file/fGDRrzfQILMFmfxyhaiKlQ/Chat-App-Mood-Board?node-id=0-1&t=RZYssx3xUn9TIS0N-0](https://github.com/orgs/chingu-voyages/projects/84/views/url))

**Comment by alekzandriia** [comment]
Mockup updated to include features to satisfy user stories. 
🔗 [Figma Design](https://www.figma.com/file/fGDRrzfQILMFmfxyhaiKlQ/Chat-App-Mood-Board?node-id=0-1&t=nVQZw6yBRXJhEmXZ-0) (last edit March 22)
