### ISSUE TITLE
Chatroom card

### ISSUE THREAD

**Issue by shijiezhou1** [chingu-voyages/v43-tier2-team-22#27]
![Image](https://user-images.githubusercontent.com/28111591/227948250-22199f5a-3465-47a7-a012-ed360d274d4e.png)

**Comment by shijiezhou1** [comment]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/28111591/228111498-d6b4f747-0a25-4596-9cbe-d5dcfd2fa9d0.png">

Chatroom card contain three parameters, chat room number, active users, and join action.

**Comment by alekzandriia** [comment]
Looks good so far. 😊
Just wondering --should the image be passed as a prop as well? Since it'll be different for each room card based on the room's topic.
Also, we should probably keep the file names consistent, so maybe change `index.js` to `ChatCard.js`

**Comment by shijiezhou1** [comment]
> 

Sure. I had updated it.
